import os
import subprocess
import time
import random
import string
import json

def run_cmd(cmd, check=True):
    print(f"[LOOP] Esecuzione: {cmd}")
    result = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    if check and result.returncode != 0:
        print(f"[ERRORE] Comando fallito: {cmd}")
        print(result.stderr)
        return False, result.stdout, result.stderr
    return True, result.stdout, result.stderr

def generate_branch_name():
    random_str = ''.join(random.choices(string.ascii_lowercase + string.digits, k=6))
    return f"agent-fix-{random_str}"

def main():
    print("=== Avvio Ciclo Loop Agentico di Contribuzione (OpenCode) ===")
    
    # 1. Checkout e aggiornamento
    run_cmd("git checkout main")
    run_cmd("git pull origin main")
    
    # 2. Task ad opencode
    # Utilizziamo opencode in modalità --variant max e con --yolo (o parametri simili auto-approvanti)
    prompt = (
        "Sei l'agente contributore autonomo. "
        "Analizza il repository e in particolare ANALYSIS_OPENCODE.md o i FIXME/TODO nel codice. "
        "Scegli un piccolo problema (es. refactoring, typing, docstrings, bug minore) e implementa la soluzione. "
        "Non eseguire comandi git, modifica solo i file. "
        "Crea un file temporaneo chiamato PR_INFO.json nella root del progetto contenente un JSON valido con due chiavi: "
        "'title' (titolo breve della PR) e 'body' (descrizione in markdown di cosa hai fatto e perche')."
    )
    
    # Invoca opencode come da global rules: opencode run "prompt" --variant max
    # Aggiungiamo -z o --yolo se supportato per bypassare i prompt interattivi.
    success, _, _ = run_cmd(f'opencode run "{prompt}" --variant max -z')
    if not success:
        print("[AVVISO] Opencode non ha completato con successo. Ritento al prossimo ciclo.")
        return
        
    # 3. Controllo modifiche
    _, stdout, _ = run_cmd("git status --porcelain")
    if not stdout.strip():
        print("[AVVISO] Nessuna modifica rilevata. Opencode non ha fatto cambiamenti.")
        return
        
    # 4. Estrazione info PR
    pr_title = "Automated fix by OpenCode"
    pr_body = "This PR was automatically generated by the agentic contribution loop."
    
    if os.path.exists("PR_INFO.json"):
        try:
            with open("PR_INFO.json", "r", encoding="utf-8") as f:
                pr_info = json.load(f)
                pr_title = pr_info.get("title", pr_title)
                pr_body = pr_info.get("body", pr_body)
            # Rimuove per non committare
            os.remove("PR_INFO.json")
        except Exception as e:
            print(f"[ERRORE] Lettura PR_INFO.json fallita: {e}")
            run_cmd("git checkout -- PR_INFO.json") # Se era tracciato
            if os.path.exists("PR_INFO.json"): os.remove("PR_INFO.json")

    # Double check modifiche (perché abbiamo appena cancellato un file)
    _, stdout, _ = run_cmd("git status --porcelain")
    if not stdout.strip():
        print("[AVVISO] Nessuna modifica rimasta dopo pulizia PR_INFO.json.")
        return

    # 5. Git workflow
    branch_name = generate_branch_name()
    run_cmd(f"git checkout -b {branch_name}")
    run_cmd("git add .")
    
    # Escape per command line
    pr_title_esc = pr_title.replace('"', '\\"')
    run_cmd(f'git commit -m "{pr_title_esc}"')
    
    # Push branch
    push_success, _, push_err = run_cmd(f"git push origin {branch_name}")
    if not push_success:
        print("[ERRORE] Push fallito, esco.")
        run_cmd("git checkout main")
        return
    
    # 6. Creazione PR tramite gh CLI
    # Scriviamo il body in un file temporaneo per evitare problemi di escaping su Windows CLI
    with open("PR_BODY.txt", "w", encoding="utf-8") as f:
        f.write(pr_body)
        
    gh_cmd = f'gh pr create --title "{pr_title_esc}" --body-file PR_BODY.txt --head {branch_name} --base main'
    gh_success, pr_stdout, _ = run_cmd(gh_cmd)
    
    if os.path.exists("PR_BODY.txt"):
        os.remove("PR_BODY.txt")
        
    if gh_success:
        print(f"[SUCCESSO] PR creata: {pr_stdout.strip()}")
    else:
        print("[ERRORE] Creazione PR fallita.")
        
    # Ritorna a main per il prossimo giro
    run_cmd("git checkout main")

if __name__ == "__main__":
    # Loop infinito, ogni X ore (es. 2 ore)
    # Può essere lanciato in background, tmux, o Windows Task Scheduler
    try:
        while True:
            main()
            wait_seconds = 7200 # 2 ore
            print(f"=== Attendo {wait_seconds} secondi prima del prossimo giro ===")
            time.sleep(wait_seconds)
    except KeyboardInterrupt:
        print("Loop interrotto dall'utente.")
